### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by lurendrejer** [dk307/HSPI_RemoteHelper#1]
Hi.

Just stumpled into your github repo, after searching for HS3+HikVision related stuff.

When you have the time, please consider supplying appveyer-links to the binaries for your projects, in the readme.
Maybe even adding them to the Homeseer plugin store (I don't know if this is free)

anyways! keep up the good work!

**Comment by dk307** [comment]
Currently I don't have bandwidth to support my projects officially on Homeseer account. I will rebuild the appveyer binaries as they might have expired.
